// FlightGear_exchanged_data.h

#ifndef	_FLIGHTGEAR_EXCHANGED_DATA_H_
#define	_FLIGHTGEAR_EXCHANGED_DATA_H_

	#include "../uav_library/common.h"
	
	enum 
	{
		// FDM (AIRCRAFT SETTINGS)
		//	FLIGHT CONDITIONS
		FDM_FLIGHT_TIME = 0,
		FDM_TEMPERATURE,
		FDM_PRESSURE,
		//	POSITION
		FDM_LATITUDE,
		FDM_LONGITUDE,
		FDM_ALTITUDE,
		FDM_GROUND_LEVEL,
		//	ORIENTATION
		FDM_ROLL_ANGLE,
		FDM_PITCH_ANGLE,
		FDM_YAW_ANGLE,
		FDM_ROLL_RATE,
		FDM_PITCH_RATE,
		FDM_YAW_RATE,
		//	VELOCITIES
		FDM_X_BODY_VELOCITY,
		FDM_Y_BODY_VELOCITY,
		FDM_Z_BODY_VELOCITY,
		FDM_X_EARTH_VELOCITY,
		FDM_Y_EARTH_VELOCITY,
		FDM_Z_EARTH_VELOCITY,
		FDM_AIRSPEED,
		//	ACCELERATION
		FDM_X_BODY_ACCELERATION,
		FDM_Y_BODY_ACCELERATION,
		FDM_Z_BODY_ACCELERATION,
		//	ENGINE
		FDM_ENGINE_ROTATION_SPEED,
		FDM_ENGINE_THRUST,
		//  ENVIROMENT
		FDM_MAGNETIC_VARIATION,
		FDM_MAGNETIC_DIP,
		FDM_N_PROPERTIES
	};
	
	enum 
	{
		// CONTROLS
		//	FLIGHT CONTROLS
		CTRL_AILERON = 0,
		CTRL_ELEVATOR,
		CTRL_RUDDER,
		CTRL_THROTTLE,
		CTRL_N_CONTROLS
	};
	
	/* function prototypes */
	//empty
	
	/* global variables */
	//empty
	
#endif
